SELECT ID,OPERATOR,FLT_NR,AC_REGISTRATION,FROM_IATA,TO_IATA,DIV_IATA,STD,ETD,ATD,STA,ETA,ATA,ONBLOCK,FROM_TERMINAL,FROM_GATE,FROM_STAND,TO_TERMINAL,TO_STAND,TO_BELT,DOOROPEN,DOORCLOSED,HULLOPEN,HULLCLOSED,AC_READY,TSAT,ASSIGNUSER,ISOTPDISMISS,PAX_BOOKED,PAX_CHECKED,PAX_BOARDED,CARGO,CAPACITY,STATUS,LAST_BAGMSGS_PROC,SEMAPHORE,CALL_SIGN,OFFBLOCK,TOBT,CTOT,HAUL_IND,AC_OWNER,SERV_TYP_COD,NI,MVT,TSAT_STATUS,CHG_REASON
FROM osusr_uuk_flt_info%year%
WHERE STD BETWEEN '%s' AND '%s'
;

SELECT ID,FLP_FILE_NAME,PLAN_NBR,CATEGORY,COMP_AT,STD,DEP_DATE,CALLSIGN,CAPTAIN,FLT_NBR,DEPARTURE_AIRP,ARRIVAL_AIRP,TAIL,AIRCRAFT_ICAO_TYPE,AIRLINE_SPEC,AUTHOR_DISPACHER,TELEX_ADDR,DISPATCH_OFFICER,PERFORMANCE_FACTOR,AVERAGE_FUEL_FLOW,TAXI_FUEL_FLOW,HOLDING_FUEL_FLOW,ROUTE_NAME,ROUTE_OPTIMIZATION,CLIMB_PROC,CLIMB_CI,CRUISE_PROC,CRUISE_CI,DESCENT_PROC,DESCENT_CI,ROUTE_DESC,GROUND_DIST,AIR_DIST,GREAT_CIRC,TRIP_FUEL,TRIP_DURATION,CONTINGENCY_FUEL,CONTINGENCY_FUEL_DURATION,TAKE_OFF_FUEL,TAKE_OFF_DURATION,TAXI_FUEL,TAXI_FUEL_DURATION,BLOCK_FUEL,BLOCK_FUEL_DURATION,LANDING_FUEL,ARRIVAL_FUEL,DRY_OP_WEIGHT,LOAD_WEIGHT,ZERO_FUEL_WEIGHT,ZERO_FUEL_W_LIMIT,TAKEOFF_WEIGHT,TAKEOFF_W_OP_LIMIT,TAKEOFF_W_STRUCT_LIMIT,LANDING_WEIGHT,LANDING_W_OP_LIMIT,LANDING_W_STRUCT_LIMIT,TS,NULL AS TAXI_OUT_TIME,NULL AS TAXI_IN_TIME,NULL AS FLIGHT_TIME
FROM osusr_fam_fp_arinc633%year% 
WHERE STR_TO_DATE(
    SUBSTRING_INDEX(SUBSTRING_INDEX(FLP_FILE_NAME, '.', 3), '.', -1),
    '%d%b%Y'
) BETWEEN  '%s' AND '%s'
;

SELECT ID,FLP_FILE_NAME,SEQUENCE,WAYPOINTID,WAYPOINT_NAME,LATITUDE,LONGITUDE,COORDINATES,AIRWAY_TYPE,AIRWAY,ALTITUDE,MINIMUM_SAFE_ALT,SEG_WIND_DIRECTION,SEG_WIND_SPEED,SEG_TEMPERATURE,SEG_ISA_DEVIATION,SPEED,TROPOPAUSE,TRUE_AIR_SPEED,MACH_NUMBER,IND_AIR_SPEED,GROUND_SPPED,OUTBOUND_TRACK_TRUE,OUTBOUND_TRACK_MAGNETIC,SEG_TRACK_TRUE,SEG_TRACK_MAGNETIC,GROUND_DISTANCE,AIR_DISTANCE,REMAIN_GROUND_DIST,REMAIN_AIR_DIST,TIME_FROM_PREV_WAY,CUMULATIVE_FLIGHT_TIME,REMAIN_FLIGHT_TIME,BURNOFF_WEIGHT,CUMULATIVE_BURNOFF_W,ESTIMATED_WEIGHT,AIRCRAFT_WEIGHT,FUELON_ON_BOAR,MINIMUM_FUEL_ONBOARD,AIRSPA_AIRSPACE_ICAO,AIRSPA_AIRSPACE_NAME,TS
FROM osusr_fam_fp_arinc633_wp%year% 
WHERE STR_TO_DATE(
    SUBSTRING_INDEX(SUBSTRING_INDEX(FLP_FILE_NAME, '.', 3), '.', -1),
    '%d%b%Y'
) BETWEEN  '%s' AND '%s'
;

SELECT ID,FLP_FILE_NAME,REFERENCE_ID,TITLE,TS
FROM osusr_fam_fp_arinc633_mel%year% 
WHERE STR_TO_DATE(
    SUBSTRING_INDEX(SUBSTRING_INDEX(FLP_FILE_NAME, '.', 3), '.', -1),
    '%d%b%Y'
) BETWEEN  '%s' AND '%s'
;

SELECT ID,ADDRESS1,ADDRESS2,DATE,FLIGHT,FLIGHTSUFFIX,AIRCRAFT,ETA,DESTINATION,FOB,LOCATION1,LOCATION2,CODE,LATITUDE,LONGITUDE,ALTITUDE,GROUNDSPEED,TEMPERATURE,WINDDIRECTION,WINDSPEED,AIRSPEED,REPORTTIME,FUEL,TS
FROM osusr_fam_tap_acars_plane%year%
WHERE REPORTTIME BETWEEN '%s' - INTERVAL 2 DAY AND '%s' + INTERVAL 2 DAY 
;
