version: '3.8'

services:
  predictor:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_SECRET_KEY=your-secret-key-here-change-in-production
      - DB_NAME=flight_ops
      - DB_USER=root
      - DB_PASSWORD=your_password_here
      - DB_HOST=localhost
      - DB_PORT=3306
      - AET_MODEL_PATH=/app/models/model.pkl
      - AET_DATA_PATH=/app/data
      - AET_LOG_PATH=/app/logs
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
